### ISSUE TITLE
Dependency not found in registry during install

### ISSUE THREAD

**Issue by abrkn** [4Catalyzer/javascript#604]
```
error Couldn't find package "tsconfig-paths@^3.9.0" required by "eslint-import-resolver-workspaces" on the "npm" registry
```

**Comment by taion** [comment]
For `eslint-import-resolver-workspaces`? Can you try again? This seems to work for me.

**Comment by abrkn** [comment]
This was due to my a condition with the Internet on my side. Sorry for the disturbance and keep up the good work!
